Add encoder support
adafruit/Adafruit_seesawPeripheral pull request #6
Opened 2022-03-26 04:56 UTC by jfurcean

This adds the ability to have up to 4 encoders. I tested this with 2 encoders attached to the [Adafruit ATtiny817 Breakout with seesaw](https://www.adafruit.com/product/5233) and a QT Py Haxpress using the following code based off of the [CircuitPython rotaryio example](https://github.com/adafruit/Adafruit_CircuitPython_seesaw/blob/main/examples/seesaw_simpletest.py). 

```py
import board
from adafruit_seesaw import seesaw, rotaryio

seesaw = seesaw.Seesaw(board.I2C(), addr=0x49)

seesaw_product = (seesaw.get_version() >> 16) & 0xFFFF
print("Found product {}".format(seesaw_product))
if seesaw_product != 1234:
    print("Wrong firmware loaded?  Expected 1234")

encoder1 = rotaryio.IncrementalEncoder(seesaw)
encoder2 = rotaryio.IncrementalEncoder(seesaw,encoder=1)

last_position1 = None
last_position2 = None

while True:

    position1 = encoder1.position
    position2 = encoder2.position

    if position1 != last_position1:
       last_position1 = position1
       print("Position 1: {}".format(position1))

    if position2 != last_position2:
       last_position2 = position2
       print("Position 2: {}".format(position2))

```

2022-03-26 19:44 UTC, caternuson commented
Neat! This LGTM. There are changes in #4 that will need to eventually get merged in as well. But tested on [PID 5233 breakout](https://www.adafruit.com/product/5233) with a build based on this PR as is, using the `example_encoder.ino` demo and a single [PID 377 encoder](https://www.adafruit.com/product/377) attached to pins `0` and `1`.

```python
Adafruit CircuitPython 7.1.1 on 2022-01-14; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import board
>>> i2c = board.I2C()
>>> i2c.try_lock()
True
>>> i2c.scan()
[73]
>>> i2c.unlock()
>>> from adafruit_seesaw import seesaw, rotaryio
>>> seesaw = seesaw.Seesaw(i2c, addr=73)
>>> encoder1 = rotaryio.IncrementalEncoder(seesaw)
>>> encoder1.position
0
>>> encoder1.position
-11
>>> encoder1.position
5
>>> 
```

2022-03-28 00:42 UTC, ladyada commented
oh hey wow you beat me to it! lol - will check this out....we have a quad encoder board that we'd like to get out so this is very nice of you :)

2023-04-12 21:29 UTC, caternuson requested changes

2023-04-12 21:29 UTC, caternuson commented on Adafruit_seesawPeripheral.h
> +    g_enc_flags[CONFIG_NUM_ENCODERS] = 0;
array indices should be `encodernum` inside the loop

2023-04-13 15:42 UTC, ladyada commented
@caternuson you can merge if good now
@jfurcean thank you so much!!! we had a design for a quad-encoder board using samd09 that got delayed by chip shortages but we can revive it now :)

2023-04-14 20:20 UTC, caternuson approved these changes

2023-04-14 20:20 UTC, merged